FROM python:alpine
COPY . /src
WORKDIR /src
RUN pip install  --index-url https://pypi.python.org/simple/ -r requirements.txt
EXPOSE 5000
CMD pip install /src/python_magic_bin-0.4.14-py2.py3-none-win32.whl
CMD python /src/app.py
